In [4]:
from numpy import random
import numpy as np

In [18]:
arr =  np.arange(8)

In [19]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
arr.reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [22]:
arr.dtype

dtype('int32')

In [5]:
arr = np.random.randn(8)
arr

array([ 0.55417154,  2.4602632 ,  1.52460586,  0.45203157, -0.59935553,
        0.90126035,  0.86330507, -1.28050978])

In [6]:
arr.sort()
arr

array([-1.28050978, -0.59935553,  0.45203157,  0.55417154,  0.86330507,
        0.90126035,  1.52460586,  2.4602632 ])

In [7]:
arr2 = np.sort(arr)
arr

array([-1.28050978, -0.59935553,  0.45203157,  0.55417154,  0.86330507,
        0.90126035,  1.52460586,  2.4602632 ])

In [9]:
arr2

array([-1.28050978, -0.59935553,  0.45203157,  0.55417154,  0.86330507,
        0.90126035,  1.52460586,  2.4602632 ])

AttributeError: 'numpy.ndarray' object has no attribute 'reverse'